In [19]:
from skimage import data, transform
import napari
import numpy as np
import pandas as pd

In [20]:
import skimage
skimage.__version__

'0.19.2'

In [21]:
image0 = data.camera()
image1 = transform.rotate(image0, 60)

viewer = napari.Viewer()
l0 = viewer.add_image(image0, colormap='green', blending='additive')
l1 = viewer.add_image(image1, colormap='magenta', blending='additive')

C:\Users\kmkedz\.conda\envs\napari-tests\lib\site-packages\napari_tools_menu\__init__.py:165: FutureWarning: Public access to Window.qt_viewer is deprecated and will be removed in
v0.5.0. It is considered an "implementation detail" of the napari
application, not part of the napari viewer model. If your use case
requires access to qt_viewer, please open an issue to discuss.
  self.tools_menu = ToolsMenu(self, self.qt_viewer.viewer)
C:\Users\kmkedz\.conda\envs\napari-tests\lib\site-packages\affinder\affinder.py:28: FutureWarning: Private attribute access ('Viewer._canvas_size') in this context (e.g. inside a plugin widget or dock widget) is deprecated and will be unavailable in version 0.5.0
  viewer.camera.zoom = np.min(viewer._canvas_size) / np.max(size)
C:\Users\kmkedz\.conda\envs\napari-tests\lib\site-packages\numpy\core\numeric.py:2446: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return bool(asarray(

Using Affinder GUI:

1. Start affinder 
2. Select layers for 'reference' (image0) and 'moving'(image1)
3. model - 'similarity'
4. choose output file
5. click points

In [22]:
p1 = viewer.layers['image0_pts'].data
p1

array([[147.0711775 , 326.13620387],
       [166.86731107, 249.65114236],
       [125.47539543, 184.86379613]])

In [23]:
p2 = viewer.layers['image1_pts'].data
p2

array([[142.57205624, 197.46133568],
       [213.65817223, 176.76537786],
       [247.85149385, 110.17838313]])

In [24]:
tf = transform.estimate_transform('similarity', p2, p1)

In [25]:
tf

<SimilarityTransform(matrix=
    [[   0.53533761,    0.89828205, -106.36872802],
     [  -0.89828205,    0.53533761,  347.98888086],
     [   0.        ,    0.        ,    1.        ]]) at 0x1af8922d310>

In [26]:
test_mat = np.loadtxt(r'D:\test_mat.txt',delimiter=',')
test_mat

array([[   0.53533761,    0.89828205, -106.36872802],
       [  -0.89828205,    0.53533761,  347.98888086],
       [   0.        ,    0.        ,    1.        ]])

tf is identical with the matrix saved by Affinder

In [27]:
im_alig = transform.warp(image1,tf)

In [28]:
viewer.add_image(im_alig, colormap='green', blending='additive')

<Image layer 'im_alig' at 0x1af99ef4700>

In [29]:
im_alig.shape

(512, 512)

In [30]:
image0.shape

(512, 512)